// Python 3.13 OpCodes
// Auto-generated with manual verification required
const OpCode = require('../OpCode');
const OpCodes = require('../OpCodes');

const opcodes = [
    [0, new OpCode(OpCodes.CACHE, "CACHE")],
    [1, new OpCode(OpCodes.BEFORE_ASYNC_WITH, "BEFORE_ASYNC_WITH")],
    [2, new OpCode(OpCodes.BEFORE_WITH, "BEFORE_WITH")],
    [4, new OpCode(OpCodes.BINARY_SLICE, "BINARY_SLICE")],
    [5, new OpCode(OpCodes.BINARY_SUBSCR, "BINARY_SUBSCR")],
    [6, new OpCode(OpCodes.CHECK_EG_MATCH, "CHECK_EG_MATCH")],
    [7, new OpCode(OpCodes.CHECK_EXC_MATCH, "CHECK_EXC_MATCH")],
    [8, new OpCode(OpCodes.CLEANUP_THROW, "CLEANUP_THROW")],
    [9, new OpCode(OpCodes.DELETE_SUBSCR, "DELETE_SUBSCR")],
    [10, new OpCode(OpCodes.END_ASYNC_FOR, "END_ASYNC_FOR")],
    [11, new OpCode(OpCodes.END_FOR, "END_FOR")],
    [12, new OpCode(OpCodes.END_SEND, "END_SEND")],
    [13, new OpCode(OpCodes.EXIT_INIT_CHECK, "EXIT_INIT_CHECK")],
    [14, new OpCode(OpCodes.FORMAT_SIMPLE, "FORMAT_SIMPLE")],
    [15, new OpCode(OpCodes.FORMAT_WITH_SPEC, "FORMAT_WITH_SPEC")],
    [16, new OpCode(OpCodes.GET_AITER, "GET_AITER")],
    [17, new OpCode(OpCodes.RESERVED, "RESERVED")],
    [18, new OpCode(OpCodes.GET_ANEXT, "GET_ANEXT")],
    [19, new OpCode(OpCodes.GET_ITER, "GET_ITER")],
    [20, new OpCode(OpCodes.GET_LEN, "GET_LEN")],
    [21, new OpCode(OpCodes.GET_YIELD_FROM_ITER, "GET_YIELD_FROM_ITER")],
    [22, new OpCode(OpCodes.INTERPRETER_EXIT, "INTERPRETER_EXIT")],
    [23, new OpCode(OpCodes.LOAD_ASSERTION_ERROR, "LOAD_ASSERTION_ERROR")],
    [24, new OpCode(OpCodes.LOAD_BUILD_CLASS, "LOAD_BUILD_CLASS")],
    [25, new OpCode(OpCodes.LOAD_LOCALS, "LOAD_LOCALS")],
    [26, new OpCode(OpCodes.MAKE_FUNCTION, "MAKE_FUNCTION")],
    [27, new OpCode(OpCodes.MATCH_KEYS, "MATCH_KEYS")],
    [28, new OpCode(OpCodes.MATCH_MAPPING, "MATCH_MAPPING")],
    [29, new OpCode(OpCodes.MATCH_SEQUENCE, "MATCH_SEQUENCE")],
    [30, new OpCode(OpCodes.NOP, "NOP")],
    [31, new OpCode(OpCodes.POP_EXCEPT, "POP_EXCEPT")],
    [32, new OpCode(OpCodes.POP_TOP, "POP_TOP")],
    [33, new OpCode(OpCodes.PUSH_EXC_INFO, "PUSH_EXC_INFO")],
    [34, new OpCode(OpCodes.PUSH_NULL, "PUSH_NULL")],
    [35, new OpCode(OpCodes.RETURN_GENERATOR, "RETURN_GENERATOR")],
    [36, new OpCode(OpCodes.RETURN_VALUE, "RETURN_VALUE")],
    [37, new OpCode(OpCodes.SETUP_ANNOTATIONS, "SETUP_ANNOTATIONS")],
    [38, new OpCode(OpCodes.STORE_SLICE, "STORE_SLICE")],
    [39, new OpCode(OpCodes.STORE_SUBSCR, "STORE_SUBSCR")],
    [40, new OpCode(OpCodes.TO_BOOL, "TO_BOOL")],
    [41, new OpCode(OpCodes.UNARY_INVERT, "UNARY_INVERT")],
    [42, new OpCode(OpCodes.UNARY_NEGATIVE, "UNARY_NEGATIVE")],
    [43, new OpCode(OpCodes.UNARY_NOT, "UNARY_NOT")],
    [44, new OpCode(OpCodes.WITH_EXCEPT_START_A, "WITH_EXCEPT_START", {HasArgument: true})],
    [45, new OpCode(OpCodes.BINARY_OP_A, "BINARY_OP", {HasArgument: true})],
    [46, new OpCode(OpCodes.BUILD_CONST_KEY_MAP_A, "BUILD_CONST_KEY_MAP", {HasArgument: true})],
    [47, new OpCode(OpCodes.BUILD_LIST_A, "BUILD_LIST", {HasArgument: true})],
    [48, new OpCode(OpCodes.BUILD_MAP_A, "BUILD_MAP", {HasArgument: true})],
    [49, new OpCode(OpCodes.BUILD_SET_A, "BUILD_SET", {HasArgument: true})],
    [50, new OpCode(OpCodes.BUILD_SLICE_A, "BUILD_SLICE", {HasArgument: true})],
    [51, new OpCode(OpCodes.BUILD_STRING_A, "BUILD_STRING", {HasArgument: true})],
    [52, new OpCode(OpCodes.BUILD_TUPLE_A, "BUILD_TUPLE", {HasArgument: true})],
    [53, new OpCode(OpCodes.CALL_A, "CALL", {HasArgument: true})],
    [54, new OpCode(OpCodes.CALL_FUNCTION_EX_A, "CALL_FUNCTION_EX", {HasArgument: true})],
    [55, new OpCode(OpCodes.CALL_INTRINSIC_1_A, "CALL_INTRINSIC_1", {HasArgument: true})],
    [56, new OpCode(OpCodes.CALL_INTRINSIC_2_A, "CALL_INTRINSIC_2", {HasArgument: true})],
    [57, new OpCode(OpCodes.CALL_KW_A, "CALL_KW", {HasArgument: true})],
    [58, new OpCode(OpCodes.COMPARE_OP_A, "COMPARE_OP", {HasArgument: true})],
    [59, new OpCode(OpCodes.CONTAINS_OP_A, "CONTAINS_OP", {HasArgument: true})],
    [60, new OpCode(OpCodes.CONVERT_VALUE_A, "CONVERT_VALUE", {HasArgument: true})],
    [61, new OpCode(OpCodes.COPY_A, "COPY", {HasArgument: true})],
    [62, new OpCode(OpCodes.COPY_FREE_VARS_A, "COPY_FREE_VARS", {HasArgument: true})],
    [63, new OpCode(OpCodes.DELETE_ATTR_A, "DELETE_ATTR", {HasArgument: true})],
    [64, new OpCode(OpCodes.DELETE_DEREF_A, "DELETE_DEREF", {HasArgument: true})],
    [65, new OpCode(OpCodes.DELETE_FAST_A, "DELETE_FAST", {HasArgument: true})],
    [66, new OpCode(OpCodes.DELETE_GLOBAL_A, "DELETE_GLOBAL", {HasArgument: true})],
    [67, new OpCode(OpCodes.DELETE_NAME_A, "DELETE_NAME", {HasArgument: true})],
    [68, new OpCode(OpCodes.DICT_MERGE_A, "DICT_MERGE", {HasArgument: true})],
    [69, new OpCode(OpCodes.DICT_UPDATE_A, "DICT_UPDATE", {HasArgument: true})],
    [70, new OpCode(OpCodes.ENTER_EXECUTOR_A, "ENTER_EXECUTOR", {HasArgument: true})],
    [71, new OpCode(OpCodes.EXTENDED_ARG_A, "EXTENDED_ARG", {HasArgument: true})],
    [72, new OpCode(OpCodes.FOR_ITER_A, "FOR_ITER", {HasArgument: true})],
    [73, new OpCode(OpCodes.GET_AWAITABLE_A, "GET_AWAITABLE", {HasArgument: true})],
    [74, new OpCode(OpCodes.IMPORT_FROM_A, "IMPORT_FROM", {HasArgument: true})],
    [75, new OpCode(OpCodes.IMPORT_NAME_A, "IMPORT_NAME", {HasArgument: true})],
    [76, new OpCode(OpCodes.IS_OP_A, "IS_OP", {HasArgument: true})],
    [77, new OpCode(OpCodes.JUMP_BACKWARD_A, "JUMP_BACKWARD", {HasArgument: true})],
    [78, new OpCode(OpCodes.JUMP_BACKWARD_NO_INTERRUPT_A, "JUMP_BACKWARD_NO_INTERRUPT", {HasArgument: true})],
    [79, new OpCode(OpCodes.JUMP_FORWARD_A, "JUMP_FORWARD", {HasArgument: true})],
    [80, new OpCode(OpCodes.LIST_APPEND_A, "LIST_APPEND", {HasArgument: true})],
    [81, new OpCode(OpCodes.LIST_EXTEND_A, "LIST_EXTEND", {HasArgument: true})],
    [82, new OpCode(OpCodes.LOAD_ATTR_A, "LOAD_ATTR", {HasArgument: true})],
    [83, new OpCode(OpCodes.LOAD_CONST_A, "LOAD_CONST", {HasArgument: true, HasConstant: true})],
    [84, new OpCode(OpCodes.LOAD_DEREF_A, "LOAD_DEREF", {HasArgument: true})],
    [85, new OpCode(OpCodes.LOAD_FAST_A, "LOAD_FAST", {HasArgument: true, HasLocal: true})],
    [86, new OpCode(OpCodes.LOAD_FAST_AND_CLEAR_A, "LOAD_FAST_AND_CLEAR", {HasArgument: true, HasLocal: true})],
    [87, new OpCode(OpCodes.LOAD_FAST_CHECK_A, "LOAD_FAST_CHECK", {HasArgument: true, HasLocal: true})],
    [88, new OpCode(OpCodes.LOAD_FAST_LOAD_FAST_A, "LOAD_FAST_LOAD_FAST", {HasArgument: true, HasLocal: true})],
    [89, new OpCode(OpCodes.LOAD_FROM_DICT_OR_DEREF_A, "LOAD_FROM_DICT_OR_DEREF", {HasArgument: true, HasLocal: true, HasName: true})],
    [90, new OpCode(OpCodes.LOAD_FROM_DICT_OR_GLOBALS_A, "LOAD_FROM_DICT_OR_GLOBALS", {HasArgument: true, HasName: true})],
    [91, new OpCode(OpCodes.LOAD_GLOBAL_A, "LOAD_GLOBAL", {HasArgument: true, HasName: true})],
    [92, new OpCode(OpCodes.LOAD_NAME_A, "LOAD_NAME", {HasArgument: true, HasName: true})],
    [93, new OpCode(OpCodes.LOAD_SUPER_ATTR_A, "LOAD_SUPER_ATTR", {HasArgument: true})],
    [94, new OpCode(OpCodes.MAKE_CELL_A, "MAKE_CELL", {HasArgument: true})],
    [95, new OpCode(OpCodes.MAP_ADD_A, "MAP_ADD", {HasArgument: true})],
    [96, new OpCode(OpCodes.MATCH_CLASS_A, "MATCH_CLASS", {HasArgument: true})],
    [97, new OpCode(OpCodes.POP_JUMP_IF_FALSE_A, "POP_JUMP_IF_FALSE", {HasArgument: true})],
    [98, new OpCode(OpCodes.POP_JUMP_IF_NONE_A, "POP_JUMP_IF_NONE", {HasArgument: true})],
    [99, new OpCode(OpCodes.POP_JUMP_IF_NOT_NONE_A, "POP_JUMP_IF_NOT_NONE", {HasArgument: true})],
    [100, new OpCode(OpCodes.POP_JUMP_IF_TRUE_A, "POP_JUMP_IF_TRUE", {HasArgument: true})],
    [101, new OpCode(OpCodes.RAISE_VARARGS_A, "RAISE_VARARGS", {HasArgument: true})],
    [102, new OpCode(OpCodes.RERAISE_A, "RERAISE", {HasArgument: true})],
    [103, new OpCode(OpCodes.RETURN_CONST_A, "RETURN_CONST", {HasArgument: true})],
    [104, new OpCode(OpCodes.SEND_A, "SEND", {HasArgument: true})],
    [105, new OpCode(OpCodes.SET_ADD_A, "SET_ADD", {HasArgument: true})],
    [106, new OpCode(OpCodes.SET_FUNCTION_ATTRIBUTE_A, "SET_FUNCTION_ATTRIBUTE", {HasArgument: true})],
    [107, new OpCode(OpCodes.SET_UPDATE_A, "SET_UPDATE", {HasArgument: true})],
    [108, new OpCode(OpCodes.STORE_ATTR_A, "STORE_ATTR", {HasArgument: true, HasName: true})],
    [109, new OpCode(OpCodes.STORE_DEREF_A, "STORE_DEREF", {HasArgument: true})],
    [110, new OpCode(OpCodes.STORE_FAST_A, "STORE_FAST", {HasArgument: true, HasLocal: true})],
    [111, new OpCode(OpCodes.STORE_FAST_LOAD_FAST_A, "STORE_FAST_LOAD_FAST", {HasArgument: true, HasLocal: true})],
    [112, new OpCode(OpCodes.STORE_FAST_STORE_FAST_A, "STORE_FAST_STORE_FAST", {HasArgument: true, HasLocal: true})],
    [113, new OpCode(OpCodes.STORE_GLOBAL_A, "STORE_GLOBAL", {HasArgument: true, HasName: true})],
    [114, new OpCode(OpCodes.STORE_NAME_A, "STORE_NAME", {HasArgument: true, HasName: true})],
    [115, new OpCode(OpCodes.SWAP_A, "SWAP", {HasArgument: true})],
    [116, new OpCode(OpCodes.UNPACK_EX_A, "UNPACK_EX", {HasArgument: true})],
    [117, new OpCode(OpCodes.UNPACK_SEQUENCE_A, "UNPACK_SEQUENCE", {HasArgument: true})],
    [118, new OpCode(OpCodes.YIELD_VALUE_A, "YIELD_VALUE", {HasArgument: true})],
    [149, new OpCode(OpCodes.RESUME_A, "RESUME", {HasArgument: true})],
    [236, new OpCode(OpCodes.INSTRUMENTED_RESUME_A, "INSTRUMENTED_RESUME", {HasArgument: true})],
    [237, new OpCode(OpCodes.INSTRUMENTED_END_FOR_A, "INSTRUMENTED_END_FOR", {HasArgument: true})],
    [238, new OpCode(OpCodes.INSTRUMENTED_END_SEND_A, "INSTRUMENTED_END_SEND", {HasArgument: true})],
    [239, new OpCode(OpCodes.INSTRUMENTED_RETURN_VALUE_A, "INSTRUMENTED_RETURN_VALUE", {HasArgument: true})],
    [240, new OpCode(OpCodes.INSTRUMENTED_RETURN_CONST_A, "INSTRUMENTED_RETURN_CONST", {HasArgument: true})],
    [241, new OpCode(OpCodes.INSTRUMENTED_YIELD_VALUE_A, "INSTRUMENTED_YIELD_VALUE", {HasArgument: true})],
    [242, new OpCode(OpCodes.INSTRUMENTED_LOAD_SUPER_ATTR_A, "INSTRUMENTED_LOAD_SUPER_ATTR", {HasArgument: true})],
    [243, new OpCode(OpCodes.INSTRUMENTED_FOR_ITER_A, "INSTRUMENTED_FOR_ITER", {HasArgument: true})],
    [244, new OpCode(OpCodes.INSTRUMENTED_CALL_A, "INSTRUMENTED_CALL", {HasArgument: true})],
    [245, new OpCode(OpCodes.INSTRUMENTED_CALL_KW_A, "INSTRUMENTED_CALL_KW", {HasArgument: true})],
    [246, new OpCode(OpCodes.INSTRUMENTED_CALL_FUNCTION_EX_A, "INSTRUMENTED_CALL_FUNCTION_EX", {HasArgument: true})],
    [247, new OpCode(OpCodes.INSTRUMENTED_INSTRUCTION_A, "INSTRUMENTED_INSTRUCTION", {HasArgument: true})],
    [248, new OpCode(OpCodes.INSTRUMENTED_JUMP_FORWARD_A, "INSTRUMENTED_JUMP_FORWARD", {HasArgument: true})],
    [249, new OpCode(OpCodes.INSTRUMENTED_JUMP_BACKWARD_A, "INSTRUMENTED_JUMP_BACKWARD", {HasArgument: true})],
    [250, new OpCode(OpCodes.INSTRUMENTED_POP_JUMP_IF_TRUE_A, "INSTRUMENTED_POP_JUMP_IF_TRUE", {HasArgument: true})],
    [251, new OpCode(OpCodes.INSTRUMENTED_POP_JUMP_IF_FALSE_A, "INSTRUMENTED_POP_JUMP_IF_FALSE", {HasArgument: true})],
    [252, new OpCode(OpCodes.INSTRUMENTED_POP_JUMP_IF_NONE_A, "INSTRUMENTED_POP_JUMP_IF_NONE", {HasArgument: true})],
    [253, new OpCode(OpCodes.INSTRUMENTED_POP_JUMP_IF_NOT_NONE_A, "INSTRUMENTED_POP_JUMP_IF_NOT_NONE", {HasArgument: true})],
    [254, new OpCode(OpCodes.INSTRUMENTED_LINE_A, "INSTRUMENTED_LINE", {HasArgument: true})],
    [256, new OpCode(OpCodes.JUMP_A, "JUMP", {HasArgument: true})],
    [257, new OpCode(OpCodes.JUMP_NO_INTERRUPT_A, "JUMP_NO_INTERRUPT", {HasArgument: true})],
    [258, new OpCode(OpCodes.LOAD_CLOSURE_A, "LOAD_CLOSURE", {HasArgument: true})],
    [259, new OpCode(OpCodes.LOAD_METHOD_A, "LOAD_METHOD", {HasArgument: true})],
    [260, new OpCode(OpCodes.LOAD_SUPER_METHOD_A, "LOAD_SUPER_METHOD", {HasArgument: true})],
    [261, new OpCode(OpCodes.LOAD_ZERO_SUPER_ATTR_A, "LOAD_ZERO_SUPER_ATTR", {HasArgument: true})],
    [262, new OpCode(OpCodes.LOAD_ZERO_SUPER_METHOD_A, "LOAD_ZERO_SUPER_METHOD", {HasArgument: true})],
    [263, new OpCode(OpCodes.POP_BLOCK_A, "POP_BLOCK", {HasArgument: true})],
    [264, new OpCode(OpCodes.SETUP_CLEANUP_A, "SETUP_CLEANUP", {HasArgument: true})],
    [265, new OpCode(OpCodes.SETUP_FINALLY_A, "SETUP_FINALLY", {HasArgument: true})],
    [266, new OpCode(OpCodes.SETUP_WITH_A, "SETUP_WITH", {HasArgument: true})],
    [267, new OpCode(OpCodes.STORE_FAST_MAYBE_NULL_A, "STORE_FAST_MAYBE_NULL", {HasArgument: true})],
];

class Python3_13_OpCodes extends OpCodes {
    constructor(co) {
        super();
        this.PopulateOpCodes(opcodes);
        this.SetupByteCode(co);
    }

    PopulateOpCodes(opCodeList) {
        for (let [idx, opcode] of opCodeList) {
            this.OpCodeList[idx] = opcode;
        }
    }
}

module.exports = Python3_13_OpCodes;
